### ISSUE TITLE
Problem 15 не нужно особое отношение к диагоналям.

### ISSUE THREAD

**Issue by runewalsh** [PoppyFanboy/Project-Euler-Solutions#2]
У меня тупое заполнение таблицы в row- или column-major порядке через
```
grid[i][j] = grid[i][j - 1] + grid[i - 1][j];
```
даёт тот же ответ.

**Comment by PoppyFanboy** [comment]
Ох, да, действительно, в переборе по диагоналям нужды нет. Все, что нам нужно знать, чтобы вычислить пути до клеток на (n+1)-ом ряду - это пути до клеток на n-ном ряду. Поправил
