### ISSUE TITLE
В Problem 16 можно заебашить точную оценку через логарифм.

### ISSUE THREAD

**Issue by runewalsh** [PoppyFanboy/Project-Euler-Solutions#3]
log<sub><sub>10</sub></sub>100 = 2
log<sub><sub>10</sub></sub>1000 = 3
2 < log<sub><sub>10</sub></sub>101 < log<sub><sub>10</sub></sub>999 < 3

Видно, что запись натурального числа N в k-ичной системе счисления содержит **<sub>⌊</sub>1 + log<sub><sub>k</sub></sub>N<sub>⌋</sub>** или, альтернативно, **<sup>⌈</sup>log<sub><sub>k</sub></sub>(N + 1)<sup>⌉</sup>** цифр.

Альтернативно [2]:
Можно использовать тот факт, что на входе даётся степень, т. е. фактически сразу p = log<sub><sub>2</sub></sub>N.

По свойствам логарифма, **log<sub><sub>a</sub></sub>N = log<sub><sub>b</sub></sub>N ÷ log<sub><sub>b</sub></sub>a** (формула перехода к другому основанию).

Это означает, что можно получить log<sub><sub>10</sub></sub> от 2<sup>p</sup> как **p × log<sub><sub>10</sub></sub>2** — умножением на константу.

**Comment by PoppyFanboy** [comment]
Хорошая идея, спасибо
